name: Build and Publish LSOF Binary to a Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libc6-dev

      - name: Compile LSOF
        run: |
          ./configure
          make

      - name: Upload LSOF binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./lsof
          asset_name: lsof-binary
          asset_content_type: application/octet-stream
