name: Build and Publish LSOF Binary to a Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libc6-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LSOF
        run: |
          ./Configure
          make
          make install
          lsof -v
      
      - name: Create Release
        id: release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload LSOF binary to Release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./lsof
          asset_name: lsof-binary
          asset_content_type: application/octet-stream
